import express, { Request, Response } from 'express';
import Link from '../models/Link';
import Content from '../models/Content';
import User from '../models/User';
import { protect } from '../middleware/auth';
import { AuthRequest, ApiResponse } from '../types';

const router = express.Router();

// ========== TOGGLE SHARE LINK (PROTECTED) ==========
router.post('/share', protect, async (req: AuthRequest, res: Response<ApiResponse>) => {
  try {
    const { share } = req.body;
    const userId = req.user!._id.toString();

    if (share) {
      // If user wants to share, check if a link already exists
      let link = await Link.findOne({ userId });

      if (!link) {
        // Creates a new link, the hash is auto-generated by the pre('save') hook
        link = await Link.create({
          userId: userId,
          contentIds: [], // Alternatively, you can use this for specific content
        });
      }

      res.json({
        success: true,
        message: 'Brain link generated',
        data: {
          hash: link.hash,
        },
      });
      return;
    } else {
      // If share is false, delete the existing link
      await Link.findOneAndDelete({ userId });
      res.json({
        success: true,
        message: 'Brain link disabled',
      });
      return;
    }
  } catch (error) {
    console.error('Share link error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error while updating share link',
    });
  }
});

// ========== GET SHARED BRAIN CONTENT (PUBLIC) ==========
router.get('/:shareLink', async (req: Request, res: Response<ApiResponse>) => {
  try {
    const hash = req.params.shareLink;
    
    // 1. Find the link in DB
    const link = await Link.findOne({ hash });

    if (!link) {
      res.status(404).json({
        success: false,
        message: 'Invalid or expired share link',
      });
      return;
    }

    // 2. Fetch the user details to show whose brain it is
    const user = await User.findById(link.userId).select('username');
    if (!user) {
      res.status(404).json({
        success: false,
        message: 'User no longer exists',
      });
      return;
    }

    // 3. Fetch all content associated with the user
    const contents = await Content.find({ userId: link.userId }).sort({ createdAt: -1 });

    res.json({
      success: true,
      message: 'Brain contents fetched successfully',
      data: {
        username: user.username,
        contents: contents,
      },
    });
  } catch (error) {
    console.error('Fetch shared brain error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error while fetching shared brain',
    });
  }
});

export default router;
